// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pipelines/v1/pipeline_service.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import v1 "github.com/VideoCoin/cloud-api/profiles/v1"
import rpc "github.com/VideoCoin/cloud-api/rpc"
import _ "github.com/envoyproxy/protoc-gen-validate/validate"
import _ "github.com/gogo/protobuf/gogoproto"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreatePipelineRequest struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProfileId            v1.ProfileId `protobuf:"varint,2,opt,name=profile_id,json=profileId,proto3,enum=cloud.api.profiles.v1.ProfileId" json:"profile_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreatePipelineRequest) Reset()         { *m = CreatePipelineRequest{} }
func (m *CreatePipelineRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePipelineRequest) ProtoMessage()    {}
func (*CreatePipelineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_service_a7b3fab04d8d48ad, []int{0}
}
func (m *CreatePipelineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePipelineRequest.Unmarshal(m, b)
}
func (m *CreatePipelineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePipelineRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePipelineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePipelineRequest.Merge(dst, src)
}
func (m *CreatePipelineRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePipelineRequest.Size(m)
}
func (m *CreatePipelineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePipelineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePipelineRequest proto.InternalMessageInfo

func (m *CreatePipelineRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePipelineRequest) GetProfileId() v1.ProfileId {
	if m != nil {
		return m.ProfileId
	}
	return v1.ProfileIdNone
}

type PipelineRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PipelineRequest) Reset()         { *m = PipelineRequest{} }
func (m *PipelineRequest) String() string { return proto.CompactTextString(m) }
func (*PipelineRequest) ProtoMessage()    {}
func (*PipelineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_service_a7b3fab04d8d48ad, []int{1}
}
func (m *PipelineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipelineRequest.Unmarshal(m, b)
}
func (m *PipelineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipelineRequest.Marshal(b, m, deterministic)
}
func (dst *PipelineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineRequest.Merge(dst, src)
}
func (m *PipelineRequest) XXX_Size() int {
	return xxx_messageInfo_PipelineRequest.Size(m)
}
func (m *PipelineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineRequest proto.InternalMessageInfo

func (m *PipelineRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListResponse struct {
	Items                []*PipelineProfile `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_service_a7b3fab04d8d48ad, []int{2}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetItems() []*PipelineProfile {
	if m != nil {
		return m.Items
	}
	return nil
}

type UpdatePipelineRequest struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string         `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string         `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ClientAddress        string         `protobuf:"bytes,5,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	StreamId             uint64         `protobuf:"varint,6,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	StreamAddress        string         `protobuf:"bytes,7,opt,name=stream_address,json=streamAddress,proto3" json:"stream_address,omitempty"`
	Status               PipelineStatus `protobuf:"varint,8,opt,name=status,proto3,enum=cloud.api.pipelines.v1.PipelineStatus" json:"status,omitempty"`
	ProfileId            v1.ProfileId   `protobuf:"varint,9,opt,name=profile_id,json=profileId,proto3,enum=cloud.api.profiles.v1.ProfileId" json:"profile_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdatePipelineRequest) Reset()         { *m = UpdatePipelineRequest{} }
func (m *UpdatePipelineRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePipelineRequest) ProtoMessage()    {}
func (*UpdatePipelineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_service_a7b3fab04d8d48ad, []int{3}
}
func (m *UpdatePipelineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePipelineRequest.Unmarshal(m, b)
}
func (m *UpdatePipelineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePipelineRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePipelineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePipelineRequest.Merge(dst, src)
}
func (m *UpdatePipelineRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePipelineRequest.Size(m)
}
func (m *UpdatePipelineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePipelineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePipelineRequest proto.InternalMessageInfo

func (m *UpdatePipelineRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdatePipelineRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdatePipelineRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdatePipelineRequest) GetClientAddress() string {
	if m != nil {
		return m.ClientAddress
	}
	return ""
}

func (m *UpdatePipelineRequest) GetStreamId() uint64 {
	if m != nil {
		return m.StreamId
	}
	return 0
}

func (m *UpdatePipelineRequest) GetStreamAddress() string {
	if m != nil {
		return m.StreamAddress
	}
	return ""
}

func (m *UpdatePipelineRequest) GetStatus() PipelineStatus {
	if m != nil {
		return m.Status
	}
	return PipelineStatusIdle
}

func (m *UpdatePipelineRequest) GetProfileId() v1.ProfileId {
	if m != nil {
		return m.ProfileId
	}
	return v1.ProfileIdNone
}

func init() {
	proto.RegisterType((*CreatePipelineRequest)(nil), "cloud.api.pipelines.v1.CreatePipelineRequest")
	proto.RegisterType((*PipelineRequest)(nil), "cloud.api.pipelines.v1.PipelineRequest")
	proto.RegisterType((*ListResponse)(nil), "cloud.api.pipelines.v1.ListResponse")
	proto.RegisterType((*UpdatePipelineRequest)(nil), "cloud.api.pipelines.v1.UpdatePipelineRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PipelineServiceClient is the client API for PipelineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PipelineServiceClient interface {
	Health(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*rpc.HealthStatus, error)
	Create(ctx context.Context, in *CreatePipelineRequest, opts ...grpc.CallOption) (*PipelineProfile, error)
	Get(ctx context.Context, in *PipelineRequest, opts ...grpc.CallOption) (*PipelineProfile, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListResponse, error)
	Update(ctx context.Context, in *UpdatePipelineRequest, opts ...grpc.CallOption) (*PipelineProfile, error)
	Run(ctx context.Context, in *PipelineRequest, opts ...grpc.CallOption) (*PipelineProfile, error)
	Complete(ctx context.Context, in *PipelineRequest, opts ...grpc.CallOption) (*PipelineProfile, error)
}

type pipelineServiceClient struct {
	cc *grpc.ClientConn
}

func NewPipelineServiceClient(cc *grpc.ClientConn) PipelineServiceClient {
	return &pipelineServiceClient{cc}
}

func (c *pipelineServiceClient) Health(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*rpc.HealthStatus, error) {
	out := new(rpc.HealthStatus)
	err := c.cc.Invoke(ctx, "/cloud.api.pipelines.v1.PipelineService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) Create(ctx context.Context, in *CreatePipelineRequest, opts ...grpc.CallOption) (*PipelineProfile, error) {
	out := new(PipelineProfile)
	err := c.cc.Invoke(ctx, "/cloud.api.pipelines.v1.PipelineService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) Get(ctx context.Context, in *PipelineRequest, opts ...grpc.CallOption) (*PipelineProfile, error) {
	out := new(PipelineProfile)
	err := c.cc.Invoke(ctx, "/cloud.api.pipelines.v1.PipelineService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/cloud.api.pipelines.v1.PipelineService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) Update(ctx context.Context, in *UpdatePipelineRequest, opts ...grpc.CallOption) (*PipelineProfile, error) {
	out := new(PipelineProfile)
	err := c.cc.Invoke(ctx, "/cloud.api.pipelines.v1.PipelineService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) Run(ctx context.Context, in *PipelineRequest, opts ...grpc.CallOption) (*PipelineProfile, error) {
	out := new(PipelineProfile)
	err := c.cc.Invoke(ctx, "/cloud.api.pipelines.v1.PipelineService/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) Complete(ctx context.Context, in *PipelineRequest, opts ...grpc.CallOption) (*PipelineProfile, error) {
	out := new(PipelineProfile)
	err := c.cc.Invoke(ctx, "/cloud.api.pipelines.v1.PipelineService/Complete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PipelineServiceServer is the server API for PipelineService service.
type PipelineServiceServer interface {
	Health(context.Context, *empty.Empty) (*rpc.HealthStatus, error)
	Create(context.Context, *CreatePipelineRequest) (*PipelineProfile, error)
	Get(context.Context, *PipelineRequest) (*PipelineProfile, error)
	List(context.Context, *empty.Empty) (*ListResponse, error)
	Update(context.Context, *UpdatePipelineRequest) (*PipelineProfile, error)
	Run(context.Context, *PipelineRequest) (*PipelineProfile, error)
	Complete(context.Context, *PipelineRequest) (*PipelineProfile, error)
}

func RegisterPipelineServiceServer(s *grpc.Server, srv PipelineServiceServer) {
	s.RegisterService(&_PipelineService_serviceDesc, srv)
}

func _PipelineService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.pipelines.v1.PipelineService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).Health(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.pipelines.v1.PipelineService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).Create(ctx, req.(*CreatePipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.pipelines.v1.PipelineService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).Get(ctx, req.(*PipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.pipelines.v1.PipelineService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).List(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.pipelines.v1.PipelineService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).Update(ctx, req.(*UpdatePipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.pipelines.v1.PipelineService/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).Run(ctx, req.(*PipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.pipelines.v1.PipelineService/Complete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).Complete(ctx, req.(*PipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PipelineService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.api.pipelines.v1.PipelineService",
	HandlerType: (*PipelineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _PipelineService_Health_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _PipelineService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _PipelineService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _PipelineService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PipelineService_Update_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _PipelineService_Run_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _PipelineService_Complete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pipelines/v1/pipeline_service.proto",
}

func init() {
	proto.RegisterFile("pipelines/v1/pipeline_service.proto", fileDescriptor_pipeline_service_a7b3fab04d8d48ad)
}

var fileDescriptor_pipeline_service_a7b3fab04d8d48ad = []byte{
	// 708 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0x8e, 0x9d, 0xd4, 0x4d, 0xf6, 0xff, 0xff, 0xfe, 0x65, 0xa1, 0x21, 0x24, 0x25, 0x4a, 0x0d,
	0xb4, 0x51, 0xa5, 0xd8, 0x4a, 0x39, 0x51, 0x09, 0x50, 0x5b, 0x21, 0xa8, 0x04, 0xa2, 0x72, 0x05,
	0x07, 0x2e, 0x91, 0xeb, 0xdd, 0xa6, 0x2b, 0x39, 0xde, 0xc5, 0xbb, 0x76, 0x29, 0x08, 0x84, 0x80,
	0x37, 0xe0, 0xc2, 0xb3, 0x70, 0xea, 0x91, 0x03, 0x07, 0x24, 0x5e, 0x00, 0x15, 0x2e, 0xbc, 0x05,
	0xf2, 0xee, 0x9a, 0x46, 0x6d, 0xa2, 0xb6, 0x87, 0xde, 0x76, 0xc6, 0x33, 0xdf, 0x37, 0xf3, 0xcd,
	0x8c, 0xc1, 0x35, 0x46, 0x18, 0x0e, 0x49, 0x84, 0xb9, 0x9b, 0x76, 0xdd, 0xdc, 0xe8, 0x71, 0x1c,
	0xa7, 0x24, 0xc0, 0x0e, 0x8b, 0xa9, 0xa0, 0xb0, 0x1a, 0x84, 0x34, 0x41, 0x8e, 0xcf, 0x88, 0xf3,
	0x37, 0xdc, 0x49, 0xbb, 0xf5, 0xc6, 0xc8, 0x64, 0x95, 0x54, 0x77, 0xfb, 0x44, 0xec, 0x24, 0x5b,
	0x4e, 0x40, 0x07, 0xee, 0x53, 0x82, 0x30, 0x5d, 0xa3, 0x24, 0x72, 0x25, 0x52, 0xc7, 0x67, 0xc4,
	0x8d, 0x59, 0xe0, 0xee, 0x60, 0x3f, 0x14, 0x3b, 0x3a, 0xe1, 0xd6, 0x09, 0x09, 0x2c, 0xa6, 0xdb,
	0x24, 0xd4, 0x5c, 0xfa, 0xad, 0x53, 0x1b, 0x7d, 0x4a, 0xfb, 0x21, 0x76, 0xa5, 0xb5, 0x95, 0x6c,
	0xbb, 0x78, 0xc0, 0xc4, 0x9e, 0xfe, 0x38, 0xab, 0x3f, 0x66, 0x18, 0x7e, 0x14, 0x51, 0xe1, 0x0b,
	0x42, 0xa3, 0x3c, 0xb5, 0x33, 0xc4, 0xda, 0xa7, 0x7d, 0x7a, 0x88, 0x91, 0x59, 0xd2, 0x90, 0x2f,
	0x1d, 0xbe, 0x32, 0x14, 0x8e, 0xa3, 0x94, 0xee, 0xb1, 0x98, 0xbe, 0xd8, 0x53, 0x49, 0x41, 0xa7,
	0x8f, 0xa3, 0x4e, 0xea, 0x87, 0x04, 0xf9, 0x02, 0xbb, 0xc7, 0x1e, 0x0a, 0xc2, 0xde, 0x05, 0x33,
	0x6b, 0x31, 0xf6, 0x05, 0xde, 0xd0, 0x82, 0x79, 0xf8, 0x79, 0x82, 0xb9, 0x80, 0x57, 0x41, 0x29,
	0xf2, 0x07, 0xb8, 0x66, 0xb4, 0x8c, 0x76, 0x65, 0xb5, 0xf2, 0xf9, 0xf7, 0x7e, 0xb1, 0x14, 0x9b,
	0xd3, 0x86, 0x27, 0xdd, 0xf0, 0x2e, 0x00, 0xba, 0xed, 0x1e, 0x41, 0x35, 0xb3, 0x65, 0xb4, 0xa7,
	0x96, 0x5a, 0xce, 0xd0, 0x68, 0x72, 0x4d, 0xd2, 0xae, 0xb3, 0xa1, 0xde, 0xeb, 0xc8, 0xab, 0xb0,
	0xfc, 0x69, 0xcf, 0x81, 0xff, 0x8f, 0x52, 0x4e, 0x01, 0x93, 0x20, 0x45, 0xe8, 0x99, 0x04, 0xd9,
	0x8f, 0xc0, 0xbf, 0x0f, 0x09, 0x17, 0x1e, 0xe6, 0x8c, 0x46, 0x1c, 0xc3, 0xdb, 0x60, 0x82, 0x08,
	0x3c, 0xe0, 0x35, 0xa3, 0x55, 0x6c, 0xff, 0xb3, 0xb4, 0xe0, 0x8c, 0xde, 0x04, 0x27, 0xc7, 0xd5,
	0xbc, 0x9e, 0xca, 0xb2, 0xf7, 0x4d, 0x30, 0xf3, 0x84, 0xa1, 0x11, 0xbd, 0x1e, 0x21, 0x86, 0x97,
	0xc1, 0x64, 0xc2, 0x71, 0x9c, 0x77, 0x56, 0xf1, 0xac, 0xcc, 0x5c, 0x47, 0x10, 0x6a, 0x51, 0x4a,
	0xd2, 0xab, 0x94, 0xb8, 0x01, 0xa6, 0x82, 0x90, 0xe0, 0x48, 0xf4, 0x7c, 0x84, 0x62, 0xcc, 0x79,
	0x6d, 0x42, 0x7e, 0xfd, 0x4f, 0x79, 0x57, 0x94, 0x13, 0x36, 0x40, 0x85, 0x8b, 0x18, 0xfb, 0x83,
	0x0c, 0xd5, 0x6a, 0x19, 0xed, 0x92, 0x57, 0x56, 0x8e, 0x75, 0x94, 0x61, 0xe8, 0x8f, 0x39, 0xc6,
	0xa4, 0xc2, 0x50, 0xde, 0x1c, 0xe3, 0x0e, 0xb0, 0xb8, 0xf0, 0x45, 0xc2, 0x6b, 0x65, 0x29, 0xf8,
	0xfc, 0x49, 0x0a, 0x6c, 0xca, 0x68, 0x4f, 0x67, 0x1d, 0x19, 0x5a, 0xe5, 0xcc, 0x43, 0x5b, 0xfa,
	0x6a, 0x1d, 0x4e, 0x6d, 0x53, 0x5d, 0x25, 0x7c, 0x0c, 0xac, 0x07, 0xf2, 0x72, 0x60, 0xd5, 0x51,
	0xcb, 0xed, 0xe4, 0x5b, 0xeb, 0xdc, 0xcb, 0x36, 0xbf, 0xde, 0x18, 0xa2, 0x88, 0x59, 0xe0, 0xa8,
	0x70, 0x55, 0x9b, 0x3d, 0xfd, 0xee, 0xfb, 0xaf, 0x8f, 0x26, 0x80, 0x65, 0x7d, 0x7f, 0x2f, 0xe1,
	0x1b, 0x60, 0xa9, 0x95, 0x84, 0x9d, 0x71, 0xfd, 0x8d, 0x5c, 0xd9, 0xfa, 0x69, 0x17, 0xc2, 0x9e,
	0x95, 0x9c, 0x55, 0xfb, 0x82, 0x3c, 0xc3, 0xa1, 0xbf, 0x05, 0x5f, 0x36, 0x16, 0xe1, 0x2e, 0x28,
	0xde, 0xc7, 0x02, 0x9e, 0x88, 0x76, 0x66, 0xda, 0xa6, 0xa4, 0xad, 0xc1, 0xea, 0x31, 0x5a, 0xf7,
	0x15, 0x41, 0xaf, 0x61, 0x0f, 0x94, 0xb2, 0x7d, 0x1f, 0xab, 0xe3, 0xf5, 0x71, 0x44, 0xc3, 0x57,
	0x62, 0x5f, 0x91, 0x2c, 0x17, 0xe1, 0xf1, 0xe6, 0xe0, 0x7b, 0x03, 0x58, 0xea, 0x02, 0xc6, 0x4b,
	0x3b, 0xf2, 0x42, 0x4e, 0xdf, 0xe3, 0x9c, 0x64, 0x6f, 0xd4, 0xc7, 0xf4, 0x98, 0xe9, 0xfb, 0xd6,
	0x00, 0x45, 0x2f, 0x89, 0xce, 0x41, 0xe0, 0x05, 0x49, 0x3e, 0x67, 0xcf, 0x8e, 0x26, 0x77, 0xb9,
	0xf0, 0x63, 0x91, 0x95, 0xf0, 0xc1, 0x00, 0xe5, 0x35, 0x3a, 0x60, 0x21, 0x16, 0xf8, 0x1c, 0xea,
	0x98, 0x97, 0x75, 0xb4, 0xec, 0xc6, 0xd8, 0x3a, 0x28, 0x5b, 0x36, 0x16, 0x57, 0x2f, 0x7d, 0x39,
	0x68, 0x16, 0xbe, 0x1d, 0x34, 0x0b, 0x3f, 0x0e, 0x9a, 0x85, 0x4f, 0x3f, 0x9b, 0x85, 0x67, 0x66,
	0xda, 0xdd, 0xb2, 0xe4, 0xd8, 0x6f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x7b, 0xb6, 0x55,
	0x0e, 0x07, 0x00, 0x00,
}
