// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transactions/v1/action_service.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetActionsRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Limit   uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset  uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (m *GetActionsRequest) Reset()                    { *m = GetActionsRequest{} }
func (m *GetActionsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetActionsRequest) ProtoMessage()               {}
func (*GetActionsRequest) Descriptor() ([]byte, []int) { return fileDescriptorActionService, []int{0} }

func (m *GetActionsRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetActionsRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetActionsRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetActionsResponse struct {
	Transactions []*Action `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *GetActionsResponse) Reset()                    { *m = GetActionsResponse{} }
func (m *GetActionsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetActionsResponse) ProtoMessage()               {}
func (*GetActionsResponse) Descriptor() ([]byte, []int) { return fileDescriptorActionService, []int{1} }

func (m *GetActionsResponse) GetTransactions() []*Action {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type GetActionRequest struct {
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *GetActionRequest) Reset()                    { *m = GetActionRequest{} }
func (m *GetActionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetActionRequest) ProtoMessage()               {}
func (*GetActionRequest) Descriptor() ([]byte, []int) { return fileDescriptorActionService, []int{2} }

func (m *GetActionRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type GetActionResponse struct {
	Transaction *Action `protobuf:"bytes,1,opt,name=transaction" json:"transaction,omitempty"`
}

func (m *GetActionResponse) Reset()                    { *m = GetActionResponse{} }
func (m *GetActionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetActionResponse) ProtoMessage()               {}
func (*GetActionResponse) Descriptor() ([]byte, []int) { return fileDescriptorActionService, []int{3} }

func (m *GetActionResponse) GetTransaction() *Action {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func init() {
	proto.RegisterType((*GetActionsRequest)(nil), "cloud.api.transactions.v1.GetActionsRequest")
	proto.RegisterType((*GetActionsResponse)(nil), "cloud.api.transactions.v1.GetActionsResponse")
	proto.RegisterType((*GetActionRequest)(nil), "cloud.api.transactions.v1.GetActionRequest")
	proto.RegisterType((*GetActionResponse)(nil), "cloud.api.transactions.v1.GetActionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ActionService service

type ActionServiceClient interface {
	GetActions(ctx context.Context, in *GetActionsRequest, opts ...grpc.CallOption) (*GetActionsResponse, error)
	GetAction(ctx context.Context, in *GetActionRequest, opts ...grpc.CallOption) (*GetActionResponse, error)
}

type actionServiceClient struct {
	cc *grpc.ClientConn
}

func NewActionServiceClient(cc *grpc.ClientConn) ActionServiceClient {
	return &actionServiceClient{cc}
}

func (c *actionServiceClient) GetActions(ctx context.Context, in *GetActionsRequest, opts ...grpc.CallOption) (*GetActionsResponse, error) {
	out := new(GetActionsResponse)
	err := grpc.Invoke(ctx, "/cloud.api.transactions.v1.ActionService/GetActions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) GetAction(ctx context.Context, in *GetActionRequest, opts ...grpc.CallOption) (*GetActionResponse, error) {
	out := new(GetActionResponse)
	err := grpc.Invoke(ctx, "/cloud.api.transactions.v1.ActionService/GetAction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ActionService service

type ActionServiceServer interface {
	GetActions(context.Context, *GetActionsRequest) (*GetActionsResponse, error)
	GetAction(context.Context, *GetActionRequest) (*GetActionResponse, error)
}

func RegisterActionServiceServer(s *grpc.Server, srv ActionServiceServer) {
	s.RegisterService(&_ActionService_serviceDesc, srv)
}

func _ActionService_GetActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).GetActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.transactions.v1.ActionService/GetActions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).GetActions(ctx, req.(*GetActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_GetAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).GetAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.transactions.v1.ActionService/GetAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).GetAction(ctx, req.(*GetActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ActionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.api.transactions.v1.ActionService",
	HandlerType: (*ActionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActions",
			Handler:    _ActionService_GetActions_Handler,
		},
		{
			MethodName: "GetAction",
			Handler:    _ActionService_GetAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transactions/v1/action_service.proto",
}

func init() { proto.RegisterFile("transactions/v1/action_service.proto", fileDescriptorActionService) }

var fileDescriptorActionService = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4a, 0xeb, 0x40,
	0x14, 0xc6, 0x93, 0xb4, 0xb7, 0x97, 0x4e, 0xef, 0x85, 0x7b, 0x87, 0x22, 0x69, 0x2c, 0xa1, 0x0d,
	0x22, 0x05, 0xdb, 0x0c, 0xad, 0x4f, 0xa0, 0x22, 0xee, 0xe3, 0x46, 0xec, 0x42, 0xa6, 0xe9, 0x34,
	0x0d, 0xb4, 0x99, 0x98, 0x99, 0x64, 0x53, 0xba, 0x71, 0x29, 0xee, 0xdc, 0xf8, 0x0e, 0xbe, 0x88,
	0x4b, 0xc1, 0x17, 0x90, 0xea, 0x83, 0x48, 0x67, 0x92, 0x1a, 0xf1, 0x0f, 0xd9, 0x9d, 0x93, 0x73,
	0xbe, 0x8f, 0xdf, 0x99, 0x2f, 0x60, 0x87, 0x47, 0x38, 0x60, 0xd8, 0xe5, 0x3e, 0x0d, 0x18, 0x4a,
	0xfa, 0x48, 0x96, 0x17, 0x8c, 0x44, 0x89, 0xef, 0x12, 0x3b, 0x8c, 0x28, 0xa7, 0xb0, 0xe1, 0xce,
	0x68, 0x3c, 0xb6, 0x71, 0xe8, 0xdb, 0xf9, 0x7d, 0x3b, 0xe9, 0x1b, 0x3d, 0xcf, 0xe7, 0xd3, 0x78,
	0x64, 0xbb, 0x74, 0x8e, 0x3c, 0xea, 0x51, 0x24, 0x14, 0xa3, 0x78, 0x22, 0x3a, 0xd1, 0x88, 0x4a,
	0x3a, 0x19, 0x4d, 0x8f, 0x52, 0x6f, 0x46, 0x10, 0x0e, 0x7d, 0x84, 0x83, 0x80, 0x72, 0x2c, 0x9d,
	0xd2, 0xe9, 0xd7, 0x34, 0x72, 0x6a, 0x0d, 0xc1, 0xff, 0x13, 0xc2, 0x0f, 0xe4, 0xd4, 0x21, 0x97,
	0x31, 0x61, 0x1c, 0xea, 0xe0, 0x37, 0x1e, 0x8f, 0x23, 0xc2, 0x98, 0xae, 0xb6, 0xd4, 0x4e, 0xd5,
	0xc9, 0x5a, 0x58, 0x07, 0xbf, 0x66, 0xfe, 0xdc, 0xe7, 0xba, 0xd6, 0x52, 0x3b, 0x65, 0x47, 0x36,
	0x70, 0x0b, 0x54, 0xe8, 0x64, 0xc2, 0x08, 0xd7, 0x4b, 0xe2, 0x73, 0xda, 0x59, 0x43, 0x00, 0xf3,
	0xe6, 0x2c, 0xa4, 0x01, 0x23, 0xf0, 0x18, 0xfc, 0xc9, 0x23, 0xe9, 0x6a, 0xab, 0xd4, 0xa9, 0x0d,
	0xda, 0xf6, 0xb7, 0xef, 0x61, 0x4b, 0x07, 0xe7, 0x83, 0xcc, 0xda, 0x05, 0xff, 0x36, 0xe6, 0x19,
	0x38, 0x04, 0xe5, 0x29, 0x66, 0xd3, 0x94, 0x5a, 0xd4, 0xd6, 0x59, 0xee, 0xc2, 0x0d, 0xc3, 0x11,
	0xa8, 0xe5, 0xcc, 0xc4, 0x7e, 0x21, 0x84, 0xbc, 0x6a, 0x70, 0xaf, 0x81, 0xbf, 0xf2, 0xfb, 0xa9,
	0x4c, 0x16, 0xde, 0xa8, 0x00, 0xbc, 0x5f, 0x0c, 0xbb, 0x3f, 0x18, 0x7e, 0x7a, 0x75, 0xa3, 0x57,
	0x70, 0x5b, 0x9e, 0x60, 0xb5, 0xaf, 0x9e, 0x5e, 0x6f, 0xb5, 0x6d, 0xd8, 0x10, 0xb9, 0xaf, 0x73,
	0x95, 0x19, 0xa1, 0x45, 0x5a, 0x2c, 0xe1, 0xb5, 0x0a, 0xaa, 0x1b, 0x25, 0xdc, 0x2b, 0xe2, 0x9f,
	0xc1, 0x74, 0x8b, 0x2d, 0xa7, 0x2c, 0x96, 0x60, 0x69, 0x42, 0x23, 0x63, 0xc9, 0x49, 0xd0, 0x62,
	0x1d, 0xc3, 0xf2, 0xb0, 0xfe, 0xb0, 0x32, 0x95, 0xc7, 0x95, 0xa9, 0x3c, 0xaf, 0x4c, 0xe5, 0xee,
	0xc5, 0x54, 0xce, 0xb5, 0xa4, 0x3f, 0xaa, 0x88, 0xdf, 0x70, 0xff, 0x2d, 0x00, 0x00, 0xff, 0xff,
	0xa3, 0x04, 0xc8, 0xde, 0x34, 0x03, 0x00, 0x00,
}
