// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: emitter/v1/emitter_service.proto

package v1

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import rpc "github.com/VideoCoin/cloud-api/rpc"
import _ "github.com/envoyproxy/protoc-gen-validate/validate"
import _ "github.com/gogo/protobuf/gogoproto"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type StreamRequest struct {
	PipelineId           string   `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StreamId             uint64   `protobuf:"varint,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ClientAddress        string   `protobuf:"bytes,4,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_emitter_service_414a29ede7fa54d7, []int{0}
}
func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (dst *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(dst, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

func (m *StreamRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *StreamRequest) GetStreamId() uint64 {
	if m != nil {
		return m.StreamId
	}
	return 0
}

func (m *StreamRequest) GetClientAddress() string {
	if m != nil {
		return m.ClientAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*StreamRequest)(nil), "cloud.api.streams.v1.StreamRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmitterServiceClient is the client API for EmitterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmitterServiceClient interface {
	Health(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*rpc.HealthStatus, error)
	RequestStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ApproveStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type emitterServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmitterServiceClient(cc *grpc.ClientConn) EmitterServiceClient {
	return &emitterServiceClient{cc}
}

func (c *emitterServiceClient) Health(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*rpc.HealthStatus, error) {
	out := new(rpc.HealthStatus)
	err := c.cc.Invoke(ctx, "/cloud.api.streams.v1.EmitterService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emitterServiceClient) RequestStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/cloud.api.streams.v1.EmitterService/RequestStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emitterServiceClient) ApproveStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/cloud.api.streams.v1.EmitterService/ApproveStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emitterServiceClient) CreateStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/cloud.api.streams.v1.EmitterService/CreateStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmitterServiceServer is the server API for EmitterService service.
type EmitterServiceServer interface {
	Health(context.Context, *empty.Empty) (*rpc.HealthStatus, error)
	RequestStream(context.Context, *StreamRequest) (*empty.Empty, error)
	ApproveStream(context.Context, *StreamRequest) (*empty.Empty, error)
	CreateStream(context.Context, *StreamRequest) (*empty.Empty, error)
}

func RegisterEmitterServiceServer(s *grpc.Server, srv EmitterServiceServer) {
	s.RegisterService(&_EmitterService_serviceDesc, srv)
}

func _EmitterService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmitterServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.streams.v1.EmitterService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmitterServiceServer).Health(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmitterService_RequestStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmitterServiceServer).RequestStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.streams.v1.EmitterService/RequestStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmitterServiceServer).RequestStream(ctx, req.(*StreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmitterService_ApproveStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmitterServiceServer).ApproveStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.streams.v1.EmitterService/ApproveStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmitterServiceServer).ApproveStream(ctx, req.(*StreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmitterService_CreateStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmitterServiceServer).CreateStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.streams.v1.EmitterService/CreateStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmitterServiceServer).CreateStream(ctx, req.(*StreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmitterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.api.streams.v1.EmitterService",
	HandlerType: (*EmitterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _EmitterService_Health_Handler,
		},
		{
			MethodName: "RequestStream",
			Handler:    _EmitterService_RequestStream_Handler,
		},
		{
			MethodName: "ApproveStream",
			Handler:    _EmitterService_ApproveStream_Handler,
		},
		{
			MethodName: "CreateStream",
			Handler:    _EmitterService_CreateStream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emitter/v1/emitter_service.proto",
}

func init() {
	proto.RegisterFile("emitter/v1/emitter_service.proto", fileDescriptor_emitter_service_414a29ede7fa54d7)
}

var fileDescriptor_emitter_service_414a29ede7fa54d7 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x51, 0x41, 0x8b, 0x13, 0x31,
	0x14, 0x9e, 0x19, 0x97, 0xba, 0x1b, 0xed, 0xb2, 0x04, 0xd1, 0x65, 0x2a, 0xb5, 0x54, 0x84, 0xbd,
	0x4c, 0x42, 0xf5, 0x17, 0xd4, 0x65, 0xc1, 0x1e, 0x54, 0x68, 0xc1, 0x83, 0x97, 0x92, 0x4e, 0x9e,
	0xd3, 0xc0, 0x4c, 0x12, 0x93, 0xcc, 0x60, 0x3d, 0x7a, 0xf7, 0xe4, 0x9f, 0xf2, 0xb8, 0xe0, 0x1f,
	0x90, 0xe2, 0x0f, 0x91, 0x49, 0xa6, 0xb4, 0xa2, 0xde, 0x7a, 0xcb, 0x7b, 0xdf, 0xf7, 0xbe, 0x97,
	0xf7, 0x7d, 0x68, 0x04, 0x95, 0x70, 0x0e, 0x0c, 0x6d, 0x26, 0xb4, 0x7b, 0x2e, 0x2d, 0x98, 0x46,
	0xe4, 0x40, 0xb4, 0x51, 0x4e, 0xe1, 0x07, 0x79, 0xa9, 0x6a, 0x4e, 0x98, 0x16, 0xc4, 0x3a, 0x03,
	0xac, 0xb2, 0xa4, 0x99, 0xa4, 0x83, 0x42, 0xa9, 0xa2, 0x04, 0xea, 0x39, 0xab, 0xfa, 0x03, 0x85,
	0x4a, 0xbb, 0x4d, 0x18, 0x49, 0x1f, 0x77, 0x20, 0xd3, 0x82, 0x32, 0x29, 0x95, 0x63, 0x4e, 0x28,
	0x69, 0x3b, 0x34, 0x2b, 0x84, 0x5b, 0xd7, 0x2b, 0x92, 0xab, 0x8a, 0x16, 0xaa, 0x50, 0x7b, 0x8d,
	0xb6, 0xf2, 0x85, 0x7f, 0x75, 0x74, 0x7a, 0x40, 0x7f, 0x27, 0x38, 0xa8, 0x6b, 0x25, 0x24, 0xf5,
	0x9f, 0xca, 0xda, 0x05, 0x46, 0xe7, 0x74, 0x0d, 0xac, 0x74, 0xeb, 0x6e, 0x60, 0x7a, 0x30, 0x00,
	0xb2, 0x51, 0x1b, 0x6d, 0xd4, 0xa7, 0x4d, 0xd8, 0x92, 0x67, 0x05, 0xc8, 0xac, 0x61, 0xa5, 0xe0,
	0xcc, 0x01, 0xfd, 0xeb, 0x11, 0x24, 0xc6, 0x5f, 0x63, 0xd4, 0x5f, 0xf8, 0x63, 0xe7, 0xf0, 0xb1,
	0x06, 0xeb, 0xf0, 0x13, 0x74, 0x4f, 0x0b, 0x0d, 0xa5, 0x90, 0xb0, 0x14, 0xfc, 0x32, 0x1e, 0xc5,
	0x57, 0x67, 0x73, 0xb4, 0x6b, 0xcd, 0x38, 0x7e, 0x84, 0xee, 0xd6, 0x16, 0x4c, 0x0b, 0x26, 0x1e,
	0xec, 0xb5, 0xe5, 0x8c, 0xe3, 0x01, 0x3a, 0x0b, 0xbe, 0xb5, 0xd0, 0x9d, 0x51, 0x7c, 0x75, 0x32,
	0x3f, 0x0d, 0x8d, 0x19, 0xc7, 0xcf, 0xd0, 0x79, 0x5e, 0x0a, 0x90, 0x6e, 0xc9, 0x38, 0x37, 0x60,
	0xed, 0xe5, 0x89, 0x1f, 0xee, 0x87, 0xee, 0x34, 0x34, 0x9f, 0xdf, 0x26, 0xe8, 0xfc, 0x26, 0xa4,
	0xb3, 0x08, 0xe1, 0xe0, 0xb7, 0xa8, 0xf7, 0xca, 0x5f, 0x8d, 0x1f, 0x92, 0x60, 0x37, 0xd9, 0xf9,
	0x48, 0x6e, 0xda, 0x2c, 0xd2, 0x01, 0xd9, 0x27, 0x67, 0x74, 0x4e, 0x02, 0x7d, 0xe1, 0x98, 0xab,
	0xed, 0xf8, 0xe2, 0xcb, 0x8f, 0x5f, 0xdf, 0x12, 0x84, 0x4f, 0x3b, 0xef, 0x3e, 0xe3, 0x37, 0xa8,
	0xdf, 0x1d, 0x1b, 0x2e, 0xc7, 0x4f, 0xc9, 0xbf, 0x92, 0x27, 0x7f, 0xf8, 0x92, 0xfe, 0x67, 0xf9,
	0x38, 0x6a, 0xf5, 0xa6, 0x5a, 0x1b, 0xd5, 0xc0, 0x71, 0xf4, 0x5e, 0xa3, 0xfb, 0xd7, 0x06, 0x98,
	0x3b, 0x8e, 0xdc, 0xcb, 0x8b, 0xef, 0xdb, 0x61, 0x74, 0xbb, 0x1d, 0x46, 0x3f, 0xb7, 0xc3, 0xe8,
	0x7d, 0xd2, 0x4c, 0x56, 0x3d, 0xcf, 0x79, 0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x26, 0xe6, 0xad,
	0xb1, 0x13, 0x03, 0x00, 0x00,
}
