// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: validator/v1/validator_service.proto

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	rpc "github.com/videocoin/cloud-api/rpc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type VerifyRequest struct {
	StreamContractId      int64    `protobuf:"varint,1,opt,name=stream_contract_id,json=streamContractId,proto3" json:"stream_contract_id,omitempty"`
	StreamContractAddress string   `protobuf:"bytes,2,opt,name=stream_contract_address,json=streamContractAddress,proto3" json:"stream_contract_address,omitempty"`
	Bitrate               uint32   `protobuf:"varint,3,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	InputId               uint64   `protobuf:"varint,4,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`
	OutputId              uint64   `protobuf:"varint,5,opt,name=output_id,json=outputId,proto3" json:"output_id,omitempty"`
	InputUrl              string   `protobuf:"bytes,6,opt,name=input_url,json=inputUrl,proto3" json:"input_url,omitempty"`
	OutputUrl             string   `protobuf:"bytes,7,opt,name=output_url,json=outputUrl,proto3" json:"output_url,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b1a82488864da9d, []int{0}
}
func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetStreamContractId() int64 {
	if m != nil {
		return m.StreamContractId
	}
	return 0
}

func (m *VerifyRequest) GetStreamContractAddress() string {
	if m != nil {
		return m.StreamContractAddress
	}
	return ""
}

func (m *VerifyRequest) GetBitrate() uint32 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

func (m *VerifyRequest) GetInputId() uint64 {
	if m != nil {
		return m.InputId
	}
	return 0
}

func (m *VerifyRequest) GetOutputId() uint64 {
	if m != nil {
		return m.OutputId
	}
	return 0
}

func (m *VerifyRequest) GetInputUrl() string {
	if m != nil {
		return m.InputUrl
	}
	return ""
}

func (m *VerifyRequest) GetOutputUrl() string {
	if m != nil {
		return m.OutputUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*VerifyRequest)(nil), "cloud.api.validator.v1.VerifyRequest")
}

func init() {
	proto.RegisterFile("validator/v1/validator_service.proto", fileDescriptor_5b1a82488864da9d)
}

var fileDescriptor_5b1a82488864da9d = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x86, 0x9b, 0xee, 0xda, 0x76, 0x07, 0x16, 0xca, 0x80, 0x6b, 0x4c, 0xb5, 0x84, 0xa2, 0x90,
	0x0b, 0x77, 0x86, 0x2a, 0x78, 0xaf, 0x22, 0xd8, 0x2b, 0x21, 0xcb, 0xee, 0x85, 0x37, 0x65, 0x32,
	0x33, 0x9b, 0x0e, 0xa4, 0x99, 0x38, 0x39, 0x13, 0x58, 0x2f, 0xf5, 0x11, 0x7c, 0x0f, 0x9f, 0xc3,
	0x4b, 0xc1, 0x17, 0x90, 0xe2, 0x83, 0x48, 0x66, 0xa6, 0xbb, 0xae, 0xb8, 0x77, 0xf9, 0xf3, 0xfd,
	0xff, 0x39, 0xe1, 0xfc, 0x41, 0x4f, 0x3a, 0x56, 0x29, 0xc1, 0x40, 0x1b, 0xda, 0x2d, 0xe9, 0xb5,
	0x58, 0xb7, 0xd2, 0x74, 0x8a, 0x4b, 0xd2, 0x18, 0x0d, 0x1a, 0x9f, 0xf0, 0x4a, 0x5b, 0x41, 0x58,
	0xa3, 0xc8, 0xb5, 0x85, 0x74, 0xcb, 0x64, 0x56, 0x6a, 0x5d, 0x56, 0x92, 0x3a, 0x57, 0x61, 0x2f,
	0xa9, 0xdc, 0x36, 0x70, 0xe5, 0x43, 0xc9, 0xa3, 0x00, 0x59, 0xa3, 0x28, 0xab, 0x6b, 0x0d, 0x0c,
	0x94, 0xae, 0xdb, 0x40, 0x4f, 0x4b, 0x05, 0x1b, 0x5b, 0x10, 0xae, 0xb7, 0xb4, 0xd4, 0xa5, 0xbe,
	0x99, 0xd1, 0x2b, 0x27, 0xdc, 0x53, 0xb0, 0xd3, 0xbf, 0xec, 0x9d, 0x12, 0x52, 0x73, 0xad, 0x6a,
	0xea, 0x3e, 0xeb, 0xb4, 0x5f, 0x60, 0x1a, 0x4e, 0x37, 0x92, 0x55, 0xb0, 0xf1, 0x81, 0xc5, 0x97,
	0x21, 0x3a, 0xbe, 0x90, 0x46, 0x5d, 0x5e, 0xe5, 0xf2, 0xa3, 0x95, 0x2d, 0xe0, 0x67, 0x08, 0xb7,
	0x60, 0x24, 0xdb, 0xae, 0xb9, 0xae, 0xc1, 0x30, 0x0e, 0x6b, 0x25, 0xe2, 0x28, 0x8d, 0xb2, 0x83,
	0x7c, 0xea, 0xc9, 0x9b, 0x00, 0x56, 0x02, 0xbf, 0x44, 0x0f, 0xfe, 0x75, 0x33, 0x21, 0x8c, 0x6c,
	0xdb, 0x78, 0x98, 0x46, 0xd9, 0x51, 0x7e, 0xff, 0x76, 0xe4, 0x95, 0x87, 0x38, 0x46, 0xe3, 0x42,
	0x81, 0x61, 0x20, 0xe3, 0x83, 0x34, 0xca, 0x8e, 0xf3, 0xbd, 0xc4, 0x0f, 0xd1, 0x44, 0xd5, 0x8d,
	0x75, 0x5b, 0x0f, 0xd3, 0x28, 0x3b, 0xcc, 0xc7, 0x4e, 0xaf, 0x04, 0x9e, 0xa1, 0x23, 0x6d, 0x21,
	0xb0, 0x7b, 0x8e, 0x4d, 0xfc, 0x0b, 0x0f, 0x7d, 0xce, 0x9a, 0x2a, 0x1e, 0xb9, 0xdd, 0x7e, 0xd0,
	0xb9, 0xa9, 0xf0, 0x63, 0x84, 0x42, 0xb2, 0xa7, 0x63, 0x47, 0xc3, 0xac, 0x73, 0x53, 0x3d, 0xff,
	0x16, 0xa1, 0xe9, 0xc5, 0xbe, 0xb1, 0x33, 0xdf, 0x29, 0x7e, 0x8f, 0x46, 0xef, 0xdc, 0xa9, 0xf0,
	0x09, 0xf1, 0x1d, 0x91, 0xfd, 0xf1, 0xc9, 0xdb, 0xbe, 0xc0, 0x64, 0x46, 0x6e, 0x0a, 0x37, 0x0d,
	0x27, 0xde, 0x7e, 0x06, 0x0c, 0x6c, 0xbb, 0x98, 0x7e, 0xfe, 0xf9, 0xfb, 0xeb, 0x10, 0xe1, 0x49,
	0x38, 0xf8, 0x27, 0xbc, 0x42, 0x23, 0x7f, 0x6a, 0xfc, 0x94, 0xfc, 0xff, 0x4f, 0x21, 0xb7, 0xaa,
	0x48, 0xee, 0xd8, 0xbb, 0x18, 0xbc, 0x9e, 0x7e, 0xdf, 0xcd, 0x07, 0x3f, 0x76, 0xf3, 0xc1, 0xaf,
	0xdd, 0x7c, 0xf0, 0x61, 0xd8, 0x2d, 0x8b, 0x91, 0xf3, 0xbc, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x27, 0xa4, 0x59, 0xb0, 0xaa, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ValidatorServiceClient is the client API for ValidatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ValidatorServiceClient interface {
	Health(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*rpc.HealthStatus, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*types.Empty, error)
}

type validatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewValidatorServiceClient(cc *grpc.ClientConn) ValidatorServiceClient {
	return &validatorServiceClient{cc}
}

func (c *validatorServiceClient) Health(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*rpc.HealthStatus, error) {
	out := new(rpc.HealthStatus)
	err := c.cc.Invoke(ctx, "/cloud.api.validator.v1.ValidatorService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validatorServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/cloud.api.validator.v1.ValidatorService/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidatorServiceServer is the server API for ValidatorService service.
type ValidatorServiceServer interface {
	Health(context.Context, *types.Empty) (*rpc.HealthStatus, error)
	Verify(context.Context, *VerifyRequest) (*types.Empty, error)
}

// UnimplementedValidatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedValidatorServiceServer struct {
}

func (*UnimplementedValidatorServiceServer) Health(ctx context.Context, req *types.Empty) (*rpc.HealthStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (*UnimplementedValidatorServiceServer) Verify(ctx context.Context, req *VerifyRequest) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}

func RegisterValidatorServiceServer(s *grpc.Server, srv ValidatorServiceServer) {
	s.RegisterService(&_ValidatorService_serviceDesc, srv)
}

func _ValidatorService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatorServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.validator.v1.ValidatorService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatorServiceServer).Health(ctx, req.(*types.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValidatorService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatorServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.validator.v1.ValidatorService/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatorServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ValidatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.api.validator.v1.ValidatorService",
	HandlerType: (*ValidatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _ValidatorService_Health_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _ValidatorService_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "validator/v1/validator_service.proto",
}
