// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: manager.proto

package proto

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "github.com/gogo/protobuf/gogoproto"
	_ "github.com/mwitkow/go-proto-validators"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

func (this *AddProfileRequest) Validate() error {
	return nil
}
func (this *Heartbeat) Validate() error {
	return nil
}
func (this *GetProfileRequest) Validate() error {
	return nil
}
func (this *CheckBalanceRequest) Validate() error {
	return nil
}
func (this *CheckBalanceResponse) Validate() error {
	return nil
}
func (this *ContractAddrRequest) Validate() error {
	return nil
}
func (this *VerifyChunkRequest) Validate() error {
	return nil
}
func (this *ChunkCreatedRequest) Validate() error {
	return nil
}
func (this *StopStreamRequest) Validate() error {
	return nil
}
func (this *UpdateTranscoderStatusRequest) Validate() error {
	return nil
}
func (this *UpdateStreamStatusRequest) Validate() error {
	return nil
}
func (this *AddJobResponse) Validate() error {
	return nil
}
func (this *AddJobRequest) Validate() error {
	return nil
}
func (this *GetJobRequest) Validate() error {
	return nil
}
func (this *GetStreamRequest) Validate() error {
	return nil
}
