// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: miners/v1/miner_service.proto

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RegistrationRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistrationRequest) Reset()         { *m = RegistrationRequest{} }
func (m *RegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*RegistrationRequest) ProtoMessage()    {}
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a3d7c5a419ed72c, []int{0}
}
func (m *RegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationRequest.Unmarshal(m, b)
}
func (m *RegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationRequest.Marshal(b, m, deterministic)
}
func (m *RegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationRequest.Merge(m, src)
}
func (m *RegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_RegistrationRequest.Size(m)
}
func (m *RegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationRequest proto.InternalMessageInfo

func (m *RegistrationRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *RegistrationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (*RegistrationRequest) XXX_MessageName() string {
	return "cloud.api.miners.v1.RegistrationRequest"
}

type MinerRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinerRequest) Reset()         { *m = MinerRequest{} }
func (m *MinerRequest) String() string { return proto.CompactTextString(m) }
func (*MinerRequest) ProtoMessage()    {}
func (*MinerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a3d7c5a419ed72c, []int{1}
}
func (m *MinerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinerRequest.Unmarshal(m, b)
}
func (m *MinerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinerRequest.Marshal(b, m, deterministic)
}
func (m *MinerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinerRequest.Merge(m, src)
}
func (m *MinerRequest) XXX_Size() int {
	return xxx_messageInfo_MinerRequest.Size(m)
}
func (m *MinerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MinerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MinerRequest proto.InternalMessageInfo

func (m *MinerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (*MinerRequest) XXX_MessageName() string {
	return "cloud.api.miners.v1.MinerRequest"
}

type UpdateMinerRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMinerRequest) Reset()         { *m = UpdateMinerRequest{} }
func (m *UpdateMinerRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMinerRequest) ProtoMessage()    {}
func (*UpdateMinerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a3d7c5a419ed72c, []int{2}
}
func (m *UpdateMinerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMinerRequest.Unmarshal(m, b)
}
func (m *UpdateMinerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMinerRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMinerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMinerRequest.Merge(m, src)
}
func (m *UpdateMinerRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMinerRequest.Size(m)
}
func (m *UpdateMinerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMinerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMinerRequest proto.InternalMessageInfo

func (m *UpdateMinerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateMinerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (*UpdateMinerRequest) XXX_MessageName() string {
	return "cloud.api.miners.v1.UpdateMinerRequest"
}

type MinerResponse struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               MinerStatus       `protobuf:"varint,3,opt,name=status,proto3,enum=cloud.api.miners.v1.MinerStatus" json:"status,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SystemInfo           *SystemInfo       `protobuf:"bytes,5,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MinerResponse) Reset()         { *m = MinerResponse{} }
func (m *MinerResponse) String() string { return proto.CompactTextString(m) }
func (*MinerResponse) ProtoMessage()    {}
func (*MinerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a3d7c5a419ed72c, []int{3}
}
func (m *MinerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinerResponse.Unmarshal(m, b)
}
func (m *MinerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinerResponse.Marshal(b, m, deterministic)
}
func (m *MinerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinerResponse.Merge(m, src)
}
func (m *MinerResponse) XXX_Size() int {
	return xxx_messageInfo_MinerResponse.Size(m)
}
func (m *MinerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MinerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MinerResponse proto.InternalMessageInfo

func (m *MinerResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MinerResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MinerResponse) GetStatus() MinerStatus {
	if m != nil {
		return m.Status
	}
	return MinerStatusNew
}

func (m *MinerResponse) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *MinerResponse) GetSystemInfo() *SystemInfo {
	if m != nil {
		return m.SystemInfo
	}
	return nil
}

func (*MinerResponse) XXX_MessageName() string {
	return "cloud.api.miners.v1.MinerResponse"
}

type MinerListResponse struct {
	Items                []*MinerResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MinerListResponse) Reset()         { *m = MinerListResponse{} }
func (m *MinerListResponse) String() string { return proto.CompactTextString(m) }
func (*MinerListResponse) ProtoMessage()    {}
func (*MinerListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a3d7c5a419ed72c, []int{4}
}
func (m *MinerListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinerListResponse.Unmarshal(m, b)
}
func (m *MinerListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinerListResponse.Marshal(b, m, deterministic)
}
func (m *MinerListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinerListResponse.Merge(m, src)
}
func (m *MinerListResponse) XXX_Size() int {
	return xxx_messageInfo_MinerListResponse.Size(m)
}
func (m *MinerListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MinerListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MinerListResponse proto.InternalMessageInfo

func (m *MinerListResponse) GetItems() []*MinerResponse {
	if m != nil {
		return m.Items
	}
	return nil
}

func (*MinerListResponse) XXX_MessageName() string {
	return "cloud.api.miners.v1.MinerListResponse"
}

type PingRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SystemInfo           []byte   `protobuf:"bytes,2,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a3d7c5a419ed72c, []int{5}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *PingRequest) GetSystemInfo() []byte {
	if m != nil {
		return m.SystemInfo
	}
	return nil
}

func (*PingRequest) XXX_MessageName() string {
	return "cloud.api.miners.v1.PingRequest"
}

type PingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a3d7c5a419ed72c, []int{6}
}
func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (*PingResponse) XXX_MessageName() string {
	return "cloud.api.miners.v1.PingResponse"
}

type AssignTaskRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	TaskID               string   `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignTaskRequest) Reset()         { *m = AssignTaskRequest{} }
func (m *AssignTaskRequest) String() string { return proto.CompactTextString(m) }
func (*AssignTaskRequest) ProtoMessage()    {}
func (*AssignTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a3d7c5a419ed72c, []int{7}
}
func (m *AssignTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignTaskRequest.Unmarshal(m, b)
}
func (m *AssignTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignTaskRequest.Marshal(b, m, deterministic)
}
func (m *AssignTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignTaskRequest.Merge(m, src)
}
func (m *AssignTaskRequest) XXX_Size() int {
	return xxx_messageInfo_AssignTaskRequest.Size(m)
}
func (m *AssignTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AssignTaskRequest proto.InternalMessageInfo

func (m *AssignTaskRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *AssignTaskRequest) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

func (*AssignTaskRequest) XXX_MessageName() string {
	return "cloud.api.miners.v1.AssignTaskRequest"
}

type Tag struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a3d7c5a419ed72c, []int{8}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Tag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (*Tag) XXX_MessageName() string {
	return "cloud.api.miners.v1.Tag"
}

type SetTagsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tags                 []*Tag   `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTagsRequest) Reset()         { *m = SetTagsRequest{} }
func (m *SetTagsRequest) String() string { return proto.CompactTextString(m) }
func (*SetTagsRequest) ProtoMessage()    {}
func (*SetTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a3d7c5a419ed72c, []int{9}
}
func (m *SetTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTagsRequest.Unmarshal(m, b)
}
func (m *SetTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTagsRequest.Marshal(b, m, deterministic)
}
func (m *SetTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTagsRequest.Merge(m, src)
}
func (m *SetTagsRequest) XXX_Size() int {
	return xxx_messageInfo_SetTagsRequest.Size(m)
}
func (m *SetTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTagsRequest proto.InternalMessageInfo

func (m *SetTagsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetTagsRequest) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (*SetTagsRequest) XXX_MessageName() string {
	return "cloud.api.miners.v1.SetTagsRequest"
}

type ForceTaskListResponse struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForceTaskListResponse) Reset()         { *m = ForceTaskListResponse{} }
func (m *ForceTaskListResponse) String() string { return proto.CompactTextString(m) }
func (*ForceTaskListResponse) ProtoMessage()    {}
func (*ForceTaskListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a3d7c5a419ed72c, []int{10}
}
func (m *ForceTaskListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForceTaskListResponse.Unmarshal(m, b)
}
func (m *ForceTaskListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForceTaskListResponse.Marshal(b, m, deterministic)
}
func (m *ForceTaskListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForceTaskListResponse.Merge(m, src)
}
func (m *ForceTaskListResponse) XXX_Size() int {
	return xxx_messageInfo_ForceTaskListResponse.Size(m)
}
func (m *ForceTaskListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForceTaskListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForceTaskListResponse proto.InternalMessageInfo

func (m *ForceTaskListResponse) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (*ForceTaskListResponse) XXX_MessageName() string {
	return "cloud.api.miners.v1.ForceTaskListResponse"
}
func init() {
	proto.RegisterType((*RegistrationRequest)(nil), "cloud.api.miners.v1.RegistrationRequest")
	golang_proto.RegisterType((*RegistrationRequest)(nil), "cloud.api.miners.v1.RegistrationRequest")
	proto.RegisterType((*MinerRequest)(nil), "cloud.api.miners.v1.MinerRequest")
	golang_proto.RegisterType((*MinerRequest)(nil), "cloud.api.miners.v1.MinerRequest")
	proto.RegisterType((*UpdateMinerRequest)(nil), "cloud.api.miners.v1.UpdateMinerRequest")
	golang_proto.RegisterType((*UpdateMinerRequest)(nil), "cloud.api.miners.v1.UpdateMinerRequest")
	proto.RegisterType((*MinerResponse)(nil), "cloud.api.miners.v1.MinerResponse")
	golang_proto.RegisterType((*MinerResponse)(nil), "cloud.api.miners.v1.MinerResponse")
	proto.RegisterMapType((map[string]string)(nil), "cloud.api.miners.v1.MinerResponse.TagsEntry")
	golang_proto.RegisterMapType((map[string]string)(nil), "cloud.api.miners.v1.MinerResponse.TagsEntry")
	proto.RegisterType((*MinerListResponse)(nil), "cloud.api.miners.v1.MinerListResponse")
	golang_proto.RegisterType((*MinerListResponse)(nil), "cloud.api.miners.v1.MinerListResponse")
	proto.RegisterType((*PingRequest)(nil), "cloud.api.miners.v1.PingRequest")
	golang_proto.RegisterType((*PingRequest)(nil), "cloud.api.miners.v1.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "cloud.api.miners.v1.PingResponse")
	golang_proto.RegisterType((*PingResponse)(nil), "cloud.api.miners.v1.PingResponse")
	proto.RegisterType((*AssignTaskRequest)(nil), "cloud.api.miners.v1.AssignTaskRequest")
	golang_proto.RegisterType((*AssignTaskRequest)(nil), "cloud.api.miners.v1.AssignTaskRequest")
	proto.RegisterType((*Tag)(nil), "cloud.api.miners.v1.Tag")
	golang_proto.RegisterType((*Tag)(nil), "cloud.api.miners.v1.Tag")
	proto.RegisterType((*SetTagsRequest)(nil), "cloud.api.miners.v1.SetTagsRequest")
	golang_proto.RegisterType((*SetTagsRequest)(nil), "cloud.api.miners.v1.SetTagsRequest")
	proto.RegisterType((*ForceTaskListResponse)(nil), "cloud.api.miners.v1.ForceTaskListResponse")
	golang_proto.RegisterType((*ForceTaskListResponse)(nil), "cloud.api.miners.v1.ForceTaskListResponse")
}

func init() { proto.RegisterFile("miners/v1/miner_service.proto", fileDescriptor_1a3d7c5a419ed72c) }
func init() {
	golang_proto.RegisterFile("miners/v1/miner_service.proto", fileDescriptor_1a3d7c5a419ed72c)
}

var fileDescriptor_1a3d7c5a419ed72c = []byte{
	// 825 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x6f, 0xe2, 0x46,
	0x18, 0xc6, 0x86, 0x40, 0x78, 0xa1, 0x88, 0x1d, 0x9a, 0x95, 0xcb, 0x76, 0x81, 0x9d, 0x48, 0x2d,
	0x1b, 0xed, 0xda, 0x0a, 0x3d, 0x14, 0xed, 0x69, 0xcb, 0xb2, 0x8d, 0x90, 0x9a, 0x55, 0x64, 0x88,
	0xd4, 0xe6, 0x82, 0x26, 0x78, 0xe2, 0x8e, 0x02, 0x36, 0xf5, 0x0c, 0x54, 0xa8, 0xea, 0xa5, 0x7f,
	0xa1, 0xff, 0xa0, 0xc7, 0xfe, 0x8a, 0x1e, 0x73, 0xac, 0xd4, 0x7b, 0x54, 0x91, 0xfe, 0x90, 0x6a,
	0xc6, 0x86, 0x84, 0xc4, 0xa4, 0x34, 0xca, 0xed, 0x1d, 0xe6, 0x79, 0x9f, 0x67, 0xde, 0x0f, 0x1e,
	0xc3, 0xf3, 0x11, 0xf3, 0x68, 0xc0, 0xad, 0xe9, 0xbe, 0xa5, 0xa2, 0x3e, 0xa7, 0xc1, 0x94, 0x0d,
	0xa8, 0x39, 0x0e, 0x7c, 0xe1, 0xa3, 0xd2, 0x60, 0xe8, 0x4f, 0x1c, 0x93, 0x8c, 0x99, 0x19, 0x02,
	0xcd, 0xe9, 0x7e, 0xf9, 0x99, 0xeb, 0xfb, 0xee, 0x90, 0x5a, 0x0a, 0x72, 0x3a, 0x39, 0xb3, 0xe8,
	0x68, 0x2c, 0x66, 0x61, 0x46, 0xf9, 0xd3, 0xe8, 0x92, 0x8c, 0x99, 0x45, 0x3c, 0xcf, 0x17, 0x44,
	0x30, 0xdf, 0xe3, 0xd1, 0xed, 0x6b, 0x97, 0x89, 0xef, 0x27, 0xa7, 0xe6, 0xc0, 0x1f, 0x59, 0xae,
	0xef, 0xfa, 0xd7, 0x1c, 0xf2, 0xa4, 0x0e, 0x2a, 0x8a, 0xe0, 0x3b, 0xb7, 0x5e, 0x17, 0xfe, 0x8c,
	0x4f, 0xa0, 0x64, 0x53, 0x97, 0x71, 0x11, 0x28, 0x72, 0x9b, 0xfe, 0x30, 0xa1, 0x5c, 0xa0, 0x97,
	0x90, 0x1d, 0x0c, 0x19, 0xf5, 0x44, 0x9f, 0x39, 0x86, 0x56, 0xd3, 0xea, 0xd9, 0x56, 0x7e, 0x7e,
	0x59, 0xdd, 0x7e, 0xa7, 0x7e, 0xec, 0xb4, 0xed, 0xed, 0xf0, 0xba, 0xe3, 0x20, 0x03, 0x32, 0xc4,
	0x71, 0x02, 0xca, 0xb9, 0xa1, 0x4b, 0xa0, 0xbd, 0x38, 0xe2, 0x0a, 0xe4, 0x0f, 0xa5, 0xd4, 0x82,
	0xb4, 0x00, 0xfa, 0x82, 0xcd, 0xd6, 0x99, 0x83, 0x9b, 0x80, 0x8e, 0xc7, 0x0e, 0x11, 0xf4, 0x3e,
	0x14, 0x42, 0x90, 0xf2, 0xc8, 0x88, 0x46, 0xe4, 0x2a, 0xc6, 0xbf, 0xeb, 0xf0, 0x51, 0x94, 0xc4,
	0xc7, 0xbe, 0xc7, 0xe9, 0x26, 0x59, 0xa8, 0x09, 0x69, 0x2e, 0x88, 0x98, 0x70, 0x23, 0x59, 0xd3,
	0xea, 0x85, 0x46, 0xcd, 0x8c, 0x19, 0x89, 0xa9, 0x78, 0xbb, 0x0a, 0x67, 0x47, 0x78, 0xf4, 0x16,
	0x52, 0x82, 0xb8, 0xdc, 0x48, 0xd5, 0x92, 0xf5, 0x5c, 0xe3, 0xd5, 0xfa, 0xbc, 0xc5, 0x7b, 0xcc,
	0x1e, 0x71, 0xf9, 0x7b, 0x4f, 0x04, 0x33, 0x5b, 0x65, 0xa2, 0xb7, 0x90, 0xe3, 0x33, 0x2e, 0xe8,
	0xa8, 0xcf, 0xbc, 0x33, 0xdf, 0xd8, 0xaa, 0x69, 0xf5, 0x5c, 0xa3, 0x1a, 0x4b, 0xd4, 0x55, 0xb8,
	0x8e, 0x77, 0xe6, 0xdb, 0xc0, 0x97, 0x71, 0xf9, 0x4b, 0xc8, 0x2e, 0x49, 0x51, 0x11, 0x92, 0xe7,
	0x74, 0x16, 0xd5, 0x2b, 0x43, 0xf4, 0x31, 0x6c, 0x4d, 0xc9, 0x70, 0xb2, 0xa8, 0x38, 0x3c, 0xbc,
	0xd1, 0x9b, 0x1a, 0x3e, 0x84, 0x27, 0xea, 0x6d, 0xdf, 0x30, 0x2e, 0x96, 0xfd, 0x6a, 0xc2, 0x16,
	0x13, 0x74, 0xc4, 0x0d, 0x4d, 0x95, 0x84, 0xff, 0xbb, 0x24, 0x3b, 0x4c, 0xc0, 0xdf, 0x41, 0xee,
	0x88, 0x79, 0xee, 0x03, 0x36, 0xa5, 0xba, 0xda, 0x03, 0xf9, 0xd0, 0xfc, 0xcd, 0x12, 0x71, 0x01,
	0xf2, 0x21, 0x75, 0xa8, 0x88, 0x07, 0xf0, 0xe4, 0x2b, 0xce, 0x99, 0xeb, 0xf5, 0x08, 0x3f, 0x7f,
	0x80, 0xe0, 0x2e, 0x64, 0x04, 0xe1, 0xe7, 0x12, 0xa8, 0xba, 0xd2, 0x82, 0xf9, 0x65, 0x35, 0x2d,
	0xc9, 0x3a, 0x6d, 0x3b, 0x2d, 0xaf, 0x3a, 0x0e, 0x7e, 0x0d, 0xc9, 0x1e, 0x71, 0x37, 0xed, 0x28,
	0xfe, 0x00, 0x85, 0x2e, 0x15, 0x72, 0x12, 0xeb, 0x16, 0xf6, 0x55, 0xb4, 0x2c, 0xba, 0xea, 0xac,
	0x11, 0xdb, 0xd9, 0x1e, 0x71, 0xc3, 0xc5, 0xc0, 0x2f, 0x61, 0xe7, 0x6b, 0x3f, 0x18, 0x50, 0xf9,
	0xaa, 0x95, 0x09, 0x15, 0x21, 0xc9, 0x9c, 0x70, 0x3e, 0x59, 0x5b, 0x86, 0x8d, 0xdf, 0xb2, 0xd1,
	0xd6, 0xf3, 0x6e, 0xe8, 0x2c, 0xa8, 0x0f, 0xe9, 0x77, 0x01, 0x25, 0x82, 0xa2, 0xa7, 0x66, 0x68,
	0x16, 0xe6, 0xc2, 0x05, 0xcc, 0xf7, 0xd2, 0x49, 0xca, 0x1b, 0x0c, 0x16, 0x7f, 0xf2, 0xcb, 0x5f,
	0xff, 0xfc, 0xaa, 0x97, 0x70, 0x41, 0x39, 0xcd, 0xc2, 0x20, 0xf8, 0x1b, 0x6d, 0x0f, 0x31, 0x48,
	0x1e, 0x50, 0x81, 0x5e, 0xdc, 0xc7, 0xa2, 0xba, 0xb0, 0x91, 0xd0, 0x33, 0x25, 0xb4, 0x83, 0x4a,
	0xab, 0x42, 0xd6, 0x4f, 0xcc, 0xf9, 0x19, 0xf9, 0x90, 0x6e, 0xd3, 0x21, 0x15, 0xf4, 0xb1, 0xd4,
	0x2a, 0x4a, 0xcd, 0xd8, 0x8b, 0x53, 0x93, 0xb5, 0x4d, 0x20, 0x1d, 0xda, 0x0f, 0xfa, 0x3c, 0x96,
	0xed, 0xae, 0x37, 0xfd, 0x1f, 0xd9, 0xc6, 0x3a, 0x59, 0x06, 0x29, 0x39, 0xe7, 0x4d, 0xaa, 0xfc,
	0x6c, 0x3d, 0xe4, 0xe6, 0xaa, 0xe0, 0xa7, 0x4a, 0xb2, 0x88, 0x6e, 0x0d, 0x10, 0xfd, 0x08, 0x99,
	0x68, 0x57, 0xd1, 0x6e, 0xbc, 0xd5, 0xac, 0x6c, 0xf2, 0x46, 0xe5, 0xed, 0x2a, 0xad, 0xe7, 0x65,
	0x23, 0xa6, 0x3c, 0x4b, 0x6e, 0xb4, 0xac, 0xf1, 0x04, 0xb6, 0xc3, 0xaf, 0x0a, 0x0d, 0x50, 0x3d,
	0x96, 0x34, 0xe6, 0xa3, 0xb3, 0x91, 0x7c, 0x02, 0xd9, 0x90, 0x39, 0xa0, 0xa2, 0x35, 0xeb, 0xb4,
	0x1f, 0x6b, 0x51, 0x12, 0xe8, 0x10, 0x52, 0xd2, 0x78, 0x50, 0xfc, 0x17, 0xe1, 0x86, 0xdd, 0x95,
	0x5f, 0xdc, 0x83, 0x58, 0xd2, 0x7d, 0x00, 0xb8, 0xf6, 0x2d, 0x14, 0x3f, 0xc5, 0x3b, 0xc6, 0x56,
	0x5e, 0xf3, 0x17, 0xc6, 0x09, 0x74, 0x04, 0xf9, 0x63, 0x8f, 0x3c, 0x26, 0xe3, 0xb7, 0x50, 0x3c,
	0xa0, 0x62, 0xc5, 0x78, 0xd6, 0x5a, 0xc8, 0x5e, 0xac, 0x5a, 0xac, 0x69, 0xe1, 0x44, 0xcb, 0xb8,
	0x98, 0x57, 0x12, 0x7f, 0xce, 0x2b, 0x89, 0xbf, 0xe7, 0x95, 0xc4, 0x1f, 0x57, 0x15, 0xed, 0xe2,
	0xaa, 0xa2, 0x9d, 0xe8, 0xd3, 0xfd, 0xd3, 0xb4, 0xe2, 0xfd, 0xe2, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa5, 0x65, 0xf5, 0x7d, 0x28, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MinersServiceClient is the client API for MinersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MinersServiceClient interface {
	Create(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*MinerResponse, error)
	Get(ctx context.Context, in *MinerRequest, opts ...grpc.CallOption) (*MinerResponse, error)
	Delete(ctx context.Context, in *MinerRequest, opts ...grpc.CallOption) (*MinerResponse, error)
	Update(ctx context.Context, in *UpdateMinerRequest, opts ...grpc.CallOption) (*MinerResponse, error)
	List(ctx context.Context, in *MinerRequest, opts ...grpc.CallOption) (*MinerListResponse, error)
	SetTags(ctx context.Context, in *SetTagsRequest, opts ...grpc.CallOption) (*MinerResponse, error)
	Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*MinerResponse, error)
	GetByID(ctx context.Context, in *MinerRequest, opts ...grpc.CallOption) (*MinerResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	AssignTask(ctx context.Context, in *AssignTaskRequest, opts ...grpc.CallOption) (*types.Empty, error)
	UnassignTask(ctx context.Context, in *AssignTaskRequest, opts ...grpc.CallOption) (*types.Empty, error)
	GetForceTaskList(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*ForceTaskListResponse, error)
}

type minersServiceClient struct {
	cc *grpc.ClientConn
}

func NewMinersServiceClient(cc *grpc.ClientConn) MinersServiceClient {
	return &minersServiceClient{cc}
}

func (c *minersServiceClient) Create(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*MinerResponse, error) {
	out := new(MinerResponse)
	err := c.cc.Invoke(ctx, "/cloud.api.miners.v1.MinersService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minersServiceClient) Get(ctx context.Context, in *MinerRequest, opts ...grpc.CallOption) (*MinerResponse, error) {
	out := new(MinerResponse)
	err := c.cc.Invoke(ctx, "/cloud.api.miners.v1.MinersService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minersServiceClient) Delete(ctx context.Context, in *MinerRequest, opts ...grpc.CallOption) (*MinerResponse, error) {
	out := new(MinerResponse)
	err := c.cc.Invoke(ctx, "/cloud.api.miners.v1.MinersService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minersServiceClient) Update(ctx context.Context, in *UpdateMinerRequest, opts ...grpc.CallOption) (*MinerResponse, error) {
	out := new(MinerResponse)
	err := c.cc.Invoke(ctx, "/cloud.api.miners.v1.MinersService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minersServiceClient) List(ctx context.Context, in *MinerRequest, opts ...grpc.CallOption) (*MinerListResponse, error) {
	out := new(MinerListResponse)
	err := c.cc.Invoke(ctx, "/cloud.api.miners.v1.MinersService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minersServiceClient) SetTags(ctx context.Context, in *SetTagsRequest, opts ...grpc.CallOption) (*MinerResponse, error) {
	out := new(MinerResponse)
	err := c.cc.Invoke(ctx, "/cloud.api.miners.v1.MinersService/SetTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minersServiceClient) Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*MinerResponse, error) {
	out := new(MinerResponse)
	err := c.cc.Invoke(ctx, "/cloud.api.miners.v1.MinersService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minersServiceClient) GetByID(ctx context.Context, in *MinerRequest, opts ...grpc.CallOption) (*MinerResponse, error) {
	out := new(MinerResponse)
	err := c.cc.Invoke(ctx, "/cloud.api.miners.v1.MinersService/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minersServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/cloud.api.miners.v1.MinersService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minersServiceClient) AssignTask(ctx context.Context, in *AssignTaskRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/cloud.api.miners.v1.MinersService/AssignTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minersServiceClient) UnassignTask(ctx context.Context, in *AssignTaskRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/cloud.api.miners.v1.MinersService/UnassignTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minersServiceClient) GetForceTaskList(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*ForceTaskListResponse, error) {
	out := new(ForceTaskListResponse)
	err := c.cc.Invoke(ctx, "/cloud.api.miners.v1.MinersService/GetForceTaskList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinersServiceServer is the server API for MinersService service.
type MinersServiceServer interface {
	Create(context.Context, *types.Empty) (*MinerResponse, error)
	Get(context.Context, *MinerRequest) (*MinerResponse, error)
	Delete(context.Context, *MinerRequest) (*MinerResponse, error)
	Update(context.Context, *UpdateMinerRequest) (*MinerResponse, error)
	List(context.Context, *MinerRequest) (*MinerListResponse, error)
	SetTags(context.Context, *SetTagsRequest) (*MinerResponse, error)
	Register(context.Context, *RegistrationRequest) (*MinerResponse, error)
	GetByID(context.Context, *MinerRequest) (*MinerResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	AssignTask(context.Context, *AssignTaskRequest) (*types.Empty, error)
	UnassignTask(context.Context, *AssignTaskRequest) (*types.Empty, error)
	GetForceTaskList(context.Context, *types.Empty) (*ForceTaskListResponse, error)
}

// UnimplementedMinersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMinersServiceServer struct {
}

func (*UnimplementedMinersServiceServer) Create(ctx context.Context, req *types.Empty) (*MinerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedMinersServiceServer) Get(ctx context.Context, req *MinerRequest) (*MinerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedMinersServiceServer) Delete(ctx context.Context, req *MinerRequest) (*MinerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedMinersServiceServer) Update(ctx context.Context, req *UpdateMinerRequest) (*MinerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedMinersServiceServer) List(ctx context.Context, req *MinerRequest) (*MinerListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedMinersServiceServer) SetTags(ctx context.Context, req *SetTagsRequest) (*MinerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTags not implemented")
}
func (*UnimplementedMinersServiceServer) Register(ctx context.Context, req *RegistrationRequest) (*MinerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedMinersServiceServer) GetByID(ctx context.Context, req *MinerRequest) (*MinerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (*UnimplementedMinersServiceServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedMinersServiceServer) AssignTask(ctx context.Context, req *AssignTaskRequest) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignTask not implemented")
}
func (*UnimplementedMinersServiceServer) UnassignTask(ctx context.Context, req *AssignTaskRequest) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnassignTask not implemented")
}
func (*UnimplementedMinersServiceServer) GetForceTaskList(ctx context.Context, req *types.Empty) (*ForceTaskListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetForceTaskList not implemented")
}

func RegisterMinersServiceServer(s *grpc.Server, srv MinersServiceServer) {
	s.RegisterService(&_MinersService_serviceDesc, srv)
}

func _MinersService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinersServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.miners.v1.MinersService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinersServiceServer).Create(ctx, req.(*types.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinersService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinersServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.miners.v1.MinersService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinersServiceServer).Get(ctx, req.(*MinerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinersService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinersServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.miners.v1.MinersService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinersServiceServer).Delete(ctx, req.(*MinerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinersService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMinerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinersServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.miners.v1.MinersService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinersServiceServer).Update(ctx, req.(*UpdateMinerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinersService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinersServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.miners.v1.MinersService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinersServiceServer).List(ctx, req.(*MinerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinersService_SetTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinersServiceServer).SetTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.miners.v1.MinersService/SetTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinersServiceServer).SetTags(ctx, req.(*SetTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinersService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinersServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.miners.v1.MinersService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinersServiceServer).Register(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinersService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinersServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.miners.v1.MinersService/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinersServiceServer).GetByID(ctx, req.(*MinerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinersService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinersServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.miners.v1.MinersService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinersServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinersService_AssignTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinersServiceServer).AssignTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.miners.v1.MinersService/AssignTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinersServiceServer).AssignTask(ctx, req.(*AssignTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinersService_UnassignTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinersServiceServer).UnassignTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.miners.v1.MinersService/UnassignTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinersServiceServer).UnassignTask(ctx, req.(*AssignTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinersService_GetForceTaskList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinersServiceServer).GetForceTaskList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.miners.v1.MinersService/GetForceTaskList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinersServiceServer).GetForceTaskList(ctx, req.(*types.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _MinersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.api.miners.v1.MinersService",
	HandlerType: (*MinersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _MinersService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _MinersService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _MinersService_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _MinersService_Update_Handler,
		},
		{
			MethodName: "List",
			Handler:    _MinersService_List_Handler,
		},
		{
			MethodName: "SetTags",
			Handler:    _MinersService_SetTags_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _MinersService_Register_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _MinersService_GetByID_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _MinersService_Ping_Handler,
		},
		{
			MethodName: "AssignTask",
			Handler:    _MinersService_AssignTask_Handler,
		},
		{
			MethodName: "UnassignTask",
			Handler:    _MinersService_UnassignTask_Handler,
		},
		{
			MethodName: "GetForceTaskList",
			Handler:    _MinersService_GetForceTaskList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "miners/v1/miner_service.proto",
}
