// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: accounts/v1/account_service.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import rpc "github.com/VideoCoin/cloud-api/rpc"
import _ "github.com/gogo/protobuf/gogoproto"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateAccountRequest struct {
	OwnerID              string   `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_23c23914a1603765, []int{0}
}
func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(dst, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateAccountRequest)(nil), "cloud.api.account.v1.CreateAccountRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	Health(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*rpc.HealthStatus, error)
	Create(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*AccountProfile, error)
	Get(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AccountProfile, error)
	Refresh(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AccountProfile, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) Health(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*rpc.HealthStatus, error) {
	out := new(rpc.HealthStatus)
	err := c.cc.Invoke(ctx, "/cloud.api.account.v1.AccountService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Create(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*AccountProfile, error) {
	out := new(AccountProfile)
	err := c.cc.Invoke(ctx, "/cloud.api.account.v1.AccountService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Get(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AccountProfile, error) {
	out := new(AccountProfile)
	err := c.cc.Invoke(ctx, "/cloud.api.account.v1.AccountService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Refresh(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AccountProfile, error) {
	out := new(AccountProfile)
	err := c.cc.Invoke(ctx, "/cloud.api.account.v1.AccountService/Refresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	Health(context.Context, *empty.Empty) (*rpc.HealthStatus, error)
	Create(context.Context, *CreateAccountRequest) (*AccountProfile, error)
	Get(context.Context, *empty.Empty) (*AccountProfile, error)
	Refresh(context.Context, *empty.Empty) (*AccountProfile, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.account.v1.AccountService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Health(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.account.v1.AccountService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Create(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.account.v1.AccountService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Get(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.account.v1.AccountService/Refresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Refresh(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.api.account.v1.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _AccountService_Health_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AccountService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AccountService_Get_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _AccountService_Refresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts/v1/account_service.proto",
}

func init() {
	proto.RegisterFile("accounts/v1/account_service.proto", fileDescriptor_account_service_23c23914a1603765)
}

var fileDescriptor_account_service_23c23914a1603765 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x50, 0x41, 0x4b, 0xe3, 0x40,
	0x14, 0x4e, 0xbb, 0xd0, 0x76, 0x67, 0x61, 0x59, 0x86, 0xb2, 0xec, 0xa6, 0x4b, 0x76, 0xb7, 0x88,
	0x88, 0xd0, 0x19, 0xaa, 0x77, 0xc1, 0xd6, 0xa2, 0x3d, 0x55, 0x5a, 0xf0, 0x20, 0x42, 0x99, 0x26,
	0xd3, 0x64, 0x20, 0xcd, 0x8b, 0x93, 0x49, 0x44, 0x8f, 0xfe, 0x05, 0x2f, 0xfe, 0x24, 0x8f, 0x8a,
	0x77, 0x91, 0xe8, 0x0f, 0x91, 0x4e, 0x46, 0xea, 0x21, 0x82, 0xe0, 0xed, 0xbd, 0xf7, 0x7d, 0xef,
	0x7b, 0xef, 0xfb, 0xd0, 0x7f, 0xe6, 0xba, 0x90, 0x46, 0x2a, 0xa1, 0x59, 0x97, 0x9a, 0x7a, 0x9a,
	0x70, 0x99, 0x09, 0x97, 0x93, 0x58, 0x82, 0x02, 0xdc, 0x74, 0x43, 0x48, 0x3d, 0xc2, 0x62, 0x41,
	0x0c, 0x81, 0x64, 0x5d, 0xbb, 0xe3, 0x0b, 0x15, 0xa4, 0x33, 0xe2, 0xc2, 0x82, 0xfa, 0xe0, 0x03,
	0xd5, 0xe4, 0x59, 0x3a, 0xd7, 0x9d, 0x6e, 0x74, 0x55, 0x88, 0xd8, 0x2d, 0x1f, 0xc0, 0x0f, 0xf9,
	0x8a, 0xc5, 0x17, 0xb1, 0x3a, 0x37, 0xe0, 0x1f, 0x03, 0xb2, 0x58, 0x50, 0x16, 0x45, 0xa0, 0x98,
	0x12, 0x10, 0x25, 0x06, 0xa5, 0x6f, 0x2e, 0x1d, 0x09, 0x8f, 0x43, 0x1f, 0x44, 0x44, 0xf5, 0x53,
	0x9d, 0xe5, 0x86, 0x8c, 0x5d, 0x1a, 0x70, 0x16, 0xaa, 0xc0, 0x2c, 0xfc, 0x2e, 0xf1, 0x54, 0x40,
	0xed, 0x1d, 0xd4, 0xec, 0x4b, 0xce, 0x14, 0xdf, 0x2d, 0xc6, 0x63, 0x7e, 0x9a, 0xf2, 0x44, 0xe1,
	0x75, 0xd4, 0x80, 0xb3, 0x88, 0xcb, 0xa9, 0xf0, 0x7e, 0x55, 0xfe, 0x55, 0x36, 0xbe, 0xf6, 0xbe,
	0xe5, 0x0f, 0x7f, 0xeb, 0xa3, 0xe5, 0x6c, 0xb8, 0x37, 0xae, 0x6b, 0x70, 0xe8, 0x6d, 0xdd, 0x55,
	0xd1, 0x77, 0xb3, 0x3a, 0x29, 0x42, 0xc2, 0x23, 0x54, 0x3b, 0xd0, 0xd7, 0xf1, 0x4f, 0x52, 0xf8,
	0x20, 0xaf, 0x26, 0xc9, 0x60, 0x69, 0xd2, 0x6e, 0x91, 0x55, 0x82, 0x32, 0x76, 0x49, 0x41, 0x9f,
	0x28, 0xa6, 0xd2, 0xa4, 0xfd, 0xe3, 0xf2, 0xfe, 0xf9, 0xaa, 0x8a, 0x70, 0xc3, 0x78, 0xb8, 0xc0,
	0x27, 0xa8, 0x56, 0xfc, 0x88, 0x37, 0x49, 0x59, 0xf4, 0xa4, 0xcc, 0x81, 0xbd, 0x56, 0xce, 0x35,
	0xac, 0x43, 0x09, 0x73, 0x11, 0xf2, 0xb6, 0x85, 0x07, 0xe8, 0xcb, 0x3e, 0x57, 0xef, 0xfe, 0xfa,
	0x51, 0x99, 0x21, 0xaa, 0x8f, 0xf9, 0x5c, 0xf2, 0x24, 0xf8, 0xac, 0x54, 0xaf, 0x79, 0x93, 0x3b,
	0xd6, 0x6d, 0xee, 0x58, 0x8f, 0xb9, 0x63, 0x5d, 0x3f, 0x39, 0xd6, 0x71, 0x35, 0xeb, 0xce, 0x6a,
	0x5a, 0x6d, 0xfb, 0x25, 0x00, 0x00, 0xff, 0xff, 0x12, 0x79, 0x76, 0xd7, 0xa1, 0x02, 0x00, 0x00,
}
