// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: streams/v1/stream_service.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import rpc "github.com/VideoCoin/cloud-api/rpc"
import proto1 "github.com/VideoCoin/common/proto"
import _ "github.com/envoyproxy/protoc-gen-validate/validate"
import _ "github.com/gogo/protobuf/gogoproto"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateStreamRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStreamRequest) Reset()         { *m = CreateStreamRequest{} }
func (m *CreateStreamRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStreamRequest) ProtoMessage()    {}
func (*CreateStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_service_513464837ca9d84e, []int{0}
}
func (m *CreateStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStreamRequest.Unmarshal(m, b)
}
func (m *CreateStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStreamRequest.Marshal(b, m, deterministic)
}
func (dst *CreateStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStreamRequest.Merge(dst, src)
}
func (m *CreateStreamRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStreamRequest.Size(m)
}
func (m *CreateStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStreamRequest proto.InternalMessageInfo

func (m *CreateStreamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StreamRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_service_513464837ca9d84e, []int{1}
}
func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (dst *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(dst, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListResponse struct {
	Items                []*StreamProfile `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_service_513464837ca9d84e, []int{2}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetItems() []*StreamProfile {
	if m != nil {
		return m.Items
	}
	return nil
}

type UpdateStreamRequest struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StreamId             uint64           `protobuf:"varint,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	StreamAddress        string           `protobuf:"bytes,4,opt,name=stream_address,json=streamAddress,proto3" json:"stream_address,omitempty"`
	Status               StreamStatus     `protobuf:"varint,5,opt,name=status,proto3,enum=cloud.api.streams.v1.StreamStatus" json:"status,omitempty"`
	ProfileId            proto1.ProfileId `protobuf:"varint,6,opt,name=profile_id,json=profileId,proto3,enum=proto.ProfileId" json:"profile_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateStreamRequest) Reset()         { *m = UpdateStreamRequest{} }
func (m *UpdateStreamRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStreamRequest) ProtoMessage()    {}
func (*UpdateStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_service_513464837ca9d84e, []int{3}
}
func (m *UpdateStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStreamRequest.Unmarshal(m, b)
}
func (m *UpdateStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStreamRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStreamRequest.Merge(dst, src)
}
func (m *UpdateStreamRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStreamRequest.Size(m)
}
func (m *UpdateStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStreamRequest proto.InternalMessageInfo

func (m *UpdateStreamRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateStreamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateStreamRequest) GetStreamId() uint64 {
	if m != nil {
		return m.StreamId
	}
	return 0
}

func (m *UpdateStreamRequest) GetStreamAddress() string {
	if m != nil {
		return m.StreamAddress
	}
	return ""
}

func (m *UpdateStreamRequest) GetStatus() StreamStatus {
	if m != nil {
		return m.Status
	}
	return StreamStatusIdle
}

func (m *UpdateStreamRequest) GetProfileId() proto1.ProfileId {
	if m != nil {
		return m.ProfileId
	}
	return proto1.ProfileIdNone
}

func init() {
	proto.RegisterType((*CreateStreamRequest)(nil), "cloud.api.streams.v1.CreateStreamRequest")
	proto.RegisterType((*StreamRequest)(nil), "cloud.api.streams.v1.StreamRequest")
	proto.RegisterType((*ListResponse)(nil), "cloud.api.streams.v1.ListResponse")
	proto.RegisterType((*UpdateStreamRequest)(nil), "cloud.api.streams.v1.UpdateStreamRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamServiceClient interface {
	Health(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*rpc.HealthStatus, error)
	Create(ctx context.Context, in *CreateStreamRequest, opts ...grpc.CallOption) (*StreamProfile, error)
	Get(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*StreamProfile, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListResponse, error)
	Update(ctx context.Context, in *UpdateStreamRequest, opts ...grpc.CallOption) (*StreamProfile, error)
	Run(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*StreamProfile, error)
	Complete(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*StreamProfile, error)
}

type streamServiceClient struct {
	cc *grpc.ClientConn
}

func NewStreamServiceClient(cc *grpc.ClientConn) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) Health(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*rpc.HealthStatus, error) {
	out := new(rpc.HealthStatus)
	err := c.cc.Invoke(ctx, "/cloud.api.streams.v1.StreamService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) Create(ctx context.Context, in *CreateStreamRequest, opts ...grpc.CallOption) (*StreamProfile, error) {
	out := new(StreamProfile)
	err := c.cc.Invoke(ctx, "/cloud.api.streams.v1.StreamService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) Get(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*StreamProfile, error) {
	out := new(StreamProfile)
	err := c.cc.Invoke(ctx, "/cloud.api.streams.v1.StreamService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/cloud.api.streams.v1.StreamService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) Update(ctx context.Context, in *UpdateStreamRequest, opts ...grpc.CallOption) (*StreamProfile, error) {
	out := new(StreamProfile)
	err := c.cc.Invoke(ctx, "/cloud.api.streams.v1.StreamService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) Run(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*StreamProfile, error) {
	out := new(StreamProfile)
	err := c.cc.Invoke(ctx, "/cloud.api.streams.v1.StreamService/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) Complete(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*StreamProfile, error) {
	out := new(StreamProfile)
	err := c.cc.Invoke(ctx, "/cloud.api.streams.v1.StreamService/Complete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamServiceServer is the server API for StreamService service.
type StreamServiceServer interface {
	Health(context.Context, *empty.Empty) (*rpc.HealthStatus, error)
	Create(context.Context, *CreateStreamRequest) (*StreamProfile, error)
	Get(context.Context, *StreamRequest) (*StreamProfile, error)
	List(context.Context, *empty.Empty) (*ListResponse, error)
	Update(context.Context, *UpdateStreamRequest) (*StreamProfile, error)
	Run(context.Context, *StreamRequest) (*StreamProfile, error)
	Complete(context.Context, *StreamRequest) (*StreamProfile, error)
}

func RegisterStreamServiceServer(s *grpc.Server, srv StreamServiceServer) {
	s.RegisterService(&_StreamService_serviceDesc, srv)
}

func _StreamService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.streams.v1.StreamService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).Health(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.streams.v1.StreamService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).Create(ctx, req.(*CreateStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.streams.v1.StreamService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).Get(ctx, req.(*StreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.streams.v1.StreamService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).List(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.streams.v1.StreamService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).Update(ctx, req.(*UpdateStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.streams.v1.StreamService/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).Run(ctx, req.(*StreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.streams.v1.StreamService/Complete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).Complete(ctx, req.(*StreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StreamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.api.streams.v1.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _StreamService_Health_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _StreamService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _StreamService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _StreamService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _StreamService_Update_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _StreamService_Run_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _StreamService_Complete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "streams/v1/stream_service.proto",
}

func init() {
	proto.RegisterFile("streams/v1/stream_service.proto", fileDescriptor_stream_service_513464837ca9d84e)
}

var fileDescriptor_stream_service_513464837ca9d84e = []byte{
	// 641 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x3f, 0x6f, 0x13, 0x31,
	0x14, 0xcf, 0x25, 0xe9, 0xa9, 0x31, 0xb4, 0x14, 0x37, 0x6a, 0xc3, 0xa5, 0xa4, 0xc1, 0x08, 0x29,
	0x20, 0xc5, 0x56, 0x0b, 0x0b, 0xdd, 0xda, 0x0a, 0x41, 0x25, 0x24, 0xd0, 0x55, 0x30, 0xc0, 0x80,
	0xdc, 0xd8, 0x4d, 0x2d, 0xe5, 0xce, 0xe6, 0xec, 0x1c, 0x14, 0xc4, 0xc2, 0xc4, 0xce, 0xc2, 0x67,
	0x61, 0x62, 0x64, 0x44, 0xe2, 0x0b, 0xa0, 0xc2, 0x02, 0x9f, 0x02, 0xc5, 0x76, 0x21, 0xb4, 0x97,
	0x8a, 0x4a, 0x5d, 0x4e, 0xcf, 0xef, 0xfd, 0xde, 0xfb, 0xbd, 0x3f, 0xbf, 0x03, 0xcb, 0xda, 0x64,
	0x9c, 0x26, 0x9a, 0xe4, 0x2b, 0xc4, 0x99, 0xcf, 0x34, 0xcf, 0x72, 0xd1, 0xe3, 0x58, 0x65, 0xd2,
	0x48, 0x58, 0xef, 0x0d, 0xe4, 0x90, 0x61, 0xaa, 0x04, 0xf6, 0x50, 0x9c, 0xaf, 0x44, 0xcd, 0xbe,
	0x94, 0xfd, 0x01, 0x27, 0x16, 0xb3, 0x33, 0xdc, 0x25, 0x3c, 0x51, 0x66, 0xdf, 0xa5, 0x44, 0x4b,
	0x3e, 0x48, 0x95, 0x20, 0x34, 0x4d, 0xa5, 0xa1, 0x46, 0xc8, 0x54, 0xfb, 0x68, 0xb7, 0x2f, 0xcc,
	0xde, 0x70, 0x07, 0xf7, 0x64, 0x42, 0xfa, 0xb2, 0x2f, 0xff, 0xd6, 0x18, 0xbd, 0xec, 0xc3, 0x5a,
	0x1e, 0x4e, 0xc6, 0xe0, 0x8f, 0x05, 0xe3, 0x72, 0x53, 0x8a, 0x94, 0xd8, 0xa6, 0xba, 0x23, 0x82,
	0x4c, 0xf5, 0xc8, 0x1e, 0xa7, 0x03, 0xb3, 0x77, 0x72, 0x82, 0x4c, 0x12, 0x99, 0x3a, 0xae, 0xd1,
	0x77, 0x57, 0x0c, 0xfc, 0x84, 0xd1, 0xfa, 0x58, 0x02, 0x4f, 0x73, 0xb9, 0xaf, 0x32, 0xf9, 0x72,
	0xdf, 0x41, 0x7b, 0xdd, 0x3e, 0x4f, 0xbb, 0x39, 0x1d, 0x08, 0x46, 0x0d, 0x27, 0xc7, 0x0c, 0x5f,
	0x62, 0xf1, 0xd8, 0x16, 0x5d, 0x00, 0xdd, 0x02, 0xf3, 0x9b, 0x19, 0xa7, 0x86, 0x6f, 0x5b, 0x6f,
	0xcc, 0x9f, 0x0f, 0xb9, 0x36, 0xf0, 0x32, 0xa8, 0xa6, 0x34, 0xe1, 0x8d, 0xa0, 0x1d, 0x74, 0x6a,
	0x1b, 0xb5, 0x8f, 0x3f, 0x3f, 0x55, 0xaa, 0x59, 0x79, 0x2e, 0x88, 0xad, 0x1b, 0x2d, 0x83, 0x99,
	0x7f, 0xf1, 0xb3, 0xa0, 0x2c, 0x98, 0x43, 0xc7, 0x65, 0xc1, 0xd0, 0x16, 0x38, 0x7f, 0x5f, 0x68,
	0x13, 0x73, 0xad, 0x64, 0xaa, 0x39, 0xbc, 0x0d, 0xa6, 0x84, 0xe1, 0x89, 0x6e, 0x04, 0xed, 0x4a,
	0xe7, 0xdc, 0xea, 0x55, 0x5c, 0x74, 0x34, 0xec, 0x6a, 0x3e, 0x74, 0xc3, 0xc7, 0x2e, 0x03, 0xfd,
	0x0a, 0xc0, 0xfc, 0x23, 0xc5, 0x8e, 0xb5, 0x78, 0x84, 0x12, 0x42, 0xdf, 0x72, 0xd9, 0x7a, 0xac,
	0x0d, 0x9b, 0xa0, 0xe6, 0x35, 0x23, 0x58, 0xa3, 0xd2, 0x0e, 0x3a, 0xd5, 0x78, 0xda, 0x39, 0xb6,
	0x18, 0xbc, 0x06, 0x66, 0x7d, 0x90, 0x32, 0x96, 0x71, 0xad, 0x1b, 0x55, 0x9b, 0x3a, 0xe3, 0xbc,
	0xeb, 0xce, 0x09, 0xd7, 0x40, 0xa8, 0x0d, 0x35, 0x43, 0xdd, 0x98, 0x6a, 0x07, 0x9d, 0xd9, 0x55,
	0x74, 0x52, 0xef, 0xdb, 0x16, 0x19, 0xfb, 0x0c, 0x48, 0x00, 0xf0, 0xa7, 0x1c, 0x35, 0x10, 0xda,
	0xfc, 0x39, 0xb7, 0x79, 0xec, 0xc7, 0xdc, 0x62, 0x71, 0x4d, 0x1d, 0x9a, 0xab, 0xef, 0xc2, 0xc3,
	0xcd, 0x6e, 0x3b, 0x91, 0xc3, 0x07, 0x20, 0xbc, 0x67, 0xd5, 0x03, 0x17, 0xb0, 0x93, 0x2d, 0x3e,
	0xd4, 0x23, 0xbe, 0x33, 0xd2, 0x74, 0xd4, 0x1c, 0x6b, 0x28, 0x53, 0x3d, 0xec, 0xe0, 0xae, 0x13,
	0x34, 0xf7, 0xf6, 0xeb, 0x8f, 0xf7, 0x65, 0x00, 0xa7, 0xbd, 0x06, 0x5f, 0x41, 0x03, 0x42, 0x77,
	0x71, 0x78, 0xbd, 0x78, 0x92, 0x02, 0x3d, 0x44, 0xff, 0x73, 0x30, 0x14, 0x59, 0xae, 0x3a, 0xba,
	0x60, 0x7f, 0xac, 0x3f, 0x4a, 0xd3, 0x6b, 0xc1, 0x0d, 0x98, 0x80, 0xca, 0x5d, 0x6e, 0xe0, 0x89,
	0x75, 0x4e, 0x45, 0xb6, 0x64, 0xc9, 0x16, 0x60, 0xfd, 0x08, 0x19, 0x79, 0x2d, 0xd8, 0x1b, 0xf8,
	0x14, 0x54, 0x47, 0xfa, 0x9b, 0xb8, 0xb3, 0x09, 0x47, 0x1c, 0xd7, 0x2c, 0x5a, 0xb4, 0x0c, 0x17,
	0xe1, 0xd1, 0x71, 0x60, 0x0e, 0x42, 0x27, 0xc8, 0x49, 0x1b, 0x2c, 0x90, 0xeb, 0xa9, 0x86, 0x8a,
	0x8a, 0x87, 0xd2, 0xa0, 0x12, 0x0f, 0xd3, 0x33, 0xdc, 0x21, 0xb2, 0x74, 0x4b, 0x28, 0x2a, 0xa2,
	0x23, 0xda, 0xd0, 0xcc, 0xc0, 0x17, 0x60, 0x7a, 0x53, 0x26, 0x6a, 0xc0, 0x0d, 0x3f, 0x43, 0xe6,
	0x2b, 0x96, 0xb9, 0x89, 0x2e, 0x4d, 0x60, 0x96, 0x6a, 0xa3, 0xfe, 0xf9, 0xa0, 0x55, 0xfa, 0x72,
	0xd0, 0x2a, 0x7d, 0x3b, 0x68, 0x95, 0x3e, 0x7c, 0x6f, 0x95, 0x9e, 0x94, 0xf3, 0x95, 0x9d, 0xd0,
	0x1e, 0xf2, 0xe6, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0xbc, 0xee, 0xb0, 0x17, 0x06, 0x00,
	0x00,
}
